import images from "./images";

const HouseData = [
    {
      id: 1,
      title: "Luxury Villa in Colombo",
      category: "luxury",
      district: "Colombo",
      city: "Kottawa",
      price: "$500,000",
      image: images.card1,
    },
    {
      id: 2,
      title: "Signature Villa in Gampaha",
      category: "signature",
      district: "Gampaha",
      city: "Gampaha",
      price: "$450,000",
      image: images.card1,
    },
    {
      id: 3,
      title: "Luxury Villa in Kandy",
      category: "luxury",
      district: "Kandy",
      city: "Peradeniya",
      price: "$400,000",
      image: images.card1,
    },
    {
      id: 4,
      title: "Signature Villa in Colombo",
      category: "signature",
      district: "Colombo",
      city: "Nugegoda",
      price: "350,000 LKR",
      image: images.card1,
    },
    {
      id: 5,
      title: "Luxury Apartment in Gampaha",
      category: "luxury",
      district: "Colombo",
      city: "Kottawa",
      price: "280,000 LKR",
      image: images.card1,
    },
    {
      id: 6,
      title: "Signature House in Kandy",
      category: "signature",
      district: "Kandy",
      city: "Kandy",
      price: "320,000 LKR",
      image: images.card1,
    },
    {
      id: 7,
      title: "Luxury Villa in Gampaha",
      category: "luxury",
      district: "Gampaha",
      city: "Gampaha",
      price: "380,000 LKR",
      image: images.card1,
    },
    {
      id: 8,
      title: "Signature Villa in Kandy",
      category: "signature",
      district: "Kandy",
      city: "Peradeniya",
      price: "270,000 LKR",
      image: images.card1,
    },
    {
      id: 9,
      title: "Luxury House in Colombo",
      category: "luxury",
      district: "Colombo",
      city: "Kottawa",
      price: "500,000 LKR",
      image: images.card1,
    },
    {
      id: 10,
      title: "Signature Apartment in Gampaha",
      category: "signature",
      district: "Gampaha",
      city: "Gampaha",
      price: "230,000 LKR",
      image: images.card1,
    },
  ];
  
  export default HouseData;
  